# Generated by Django 4.2.5 on 2023-11-03 13:01

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_cake_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='contain',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='cake',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
